Fix tgz file name for DPDK packages (TGZ_FILE -> DPDK_PKGS_TGZ)

diff --git a/common/debian/contrail-install-packages/debian/rules b/common/debian/contrail-install-packages/debian/rules
--- a/common/debian/contrail-install-packages/debian/rules
+++ b/common/debian/contrail-install-packages/debian/rules
@@ -54,7 +54,7 @@ override_dh_auto_install:
 	# install TGZ file and packages list file
 	if [ -f $(TGZ_FILE) ]; then echo "Using TGZ FILE = $(TGZ_FILE)"; install -p -m 644 $(TGZ_FILE) $(buildroot)$(_contrailopt)/contrail_packages/contrail_debs.tgz; else echo "ERROR: TGZ file containing all debs is not supplied or not present"; echo "Supply Argument: FILE_LIST=<TGZ FILE>"; exit 1; fi
 	# install DPDK TGZ packages file
-	if [ -f $(TGZ_FILE) ]; then echo "Using DPDK TGZ FILE = $(TGZ_FILE)"; install -p -m 644 $(DPDK_PKGS_TGZ) $(buildroot)$(_contrailopt)/contrail_packages/contrail_dpdk_debs.tgz; else echo "ERROR: TGZ file containing all extra debs for DPDK mode is not supplied or not present"; echo "Supply Argument: DPDK_PKGS_TGZ=<TGZ FILE>"; exit 1; fi
+	if [ -f $(DPDK_PKGS_TGZ) ]; then echo "Using DPDK TGZ FILE = $(DPDK_PKGS_TGZ)"; install -p -m 644 $(DPDK_PKGS_TGZ) $(buildroot)$(_contrailopt)/contrail_packages/contrail_dpdk_debs.tgz; else echo "ERROR: TGZ file containing all extra debs for DPDK mode is not supplied or not present"; echo "Supply Argument: DPDK_PKGS_TGZ=<TGZ FILE>"; exit 1; fi
 	
 override_dh_shlibdeps:
 
